AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Facebook API Service

Parameters:
  EntityServiceBindings:
    Type: String
    Description: DynamoDB table name for entity service bindings
    Default: ieva_entity_service_bindings
  OrchestratorFunc:
    Type: String
    Description: Posting orchestration core
    Default: arn:aws:lambda:us-east-1:039612842158:function:ieva-posting-orchestrator-IevaPostingOrchestrator-LahsMOTUA6x2:$LATEST 

Globals:
  Api:
    Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Requested-With'"
        AllowOrigin: "'*'"
    GatewayResponses:
          DEFAULT_4XX:
            ResponseParameters:
              Headers:
                Access-Control-Allow-Origin: "'*'"
                Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Requested-With'"
                Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
          DEFAULT_5XX:
            ResponseParameters:
              Headers:
                Access-Control-Allow-Origin: "'*'"
                Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Requested-With'"
                Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"


Resources:
  FacebookAPIRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: FacebookAPISecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: arn:aws:secretsmanager:us-east-1:*:secret:facebook/credentials*
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:DescribeTable
                Resource:
                  - !GetAtt FacebookTokensTable.Arn
                  - arn:aws:dynamodb:us-east-1:039612842158:table/token-tracking
        - PolicyName: EventBridgePublishAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: arn:aws:events:us-east-1:039612842158:event-bus/default
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !GetAtt FacebookCommentHandler.Arn
              - Effect: Allow
                Action:
                  - events:RetrieveConnectionCredentials
                  - events:DescribeConnection
                Resource: !ImportValue RapidApiConnectionArnV3
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: 
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/*"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: "*"
                              
  FacebookAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 30
      MemorySize: 256
      Role: !GetAtt FacebookAPIRole.Arn
      Layers:
        - !Ref FacebookLayer
        - arn:aws:lambda:us-east-1:039612842158:layer:request-layer:2
        - arn:aws:lambda:us-east-1:039612842158:layer:response-layer:1
        - arn:aws:lambda:us-east-1:039612842158:layer:token-tracking-layer:46
      Environment:
        Variables:
          ALLOW_ORIGINS: "*"       
      Events:
        PostToPage:
            Type: Api
            Properties:
              Path: /post-to-page
              Method: post
        GetAccessToken:
          Type: Api
          Properties:
            Path: /get-access-token
            Method: post
        ExtendToken:
          Type: Api
          Properties:
            Path: /extend-token
            Method: post
        GetPages:
          Type: Api
          Properties:
            Path: /get-pages
            Method: get
        GetPagesInfo:
          Type: Api
          Properties:
            Path: /get_page_info
            Method: get    
        GetPagePosts:
          Type: Api
          Properties:
            Path: /get-page-feed
            Method: get   
        WebhookVerification:
          Type: Api
          Properties:
            Path: /webhook
            Method: get
        WebhookProcessing:
          Type: Api
          Properties:
            Path: /webhook
            Method: post   
        GetPageSubscriptions:
          Type: Api
          Properties:
            Path: /page-subscriptions
            Method: get
        SubscribeToPage:
          Type: Api
          Properties:
            Path: /subscribe-to-page
            Method: post     
        UnsubscribeFromPage:
          Type: Api
          Properties:
            Path: /unsubscribe-from-page
            Method: post    
        SendMessage:
          Type: Api
          Properties:
            Path: /send-message
            Method: post           
     
  FacebookCommentHandler:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: "FacebookCommentHandler"
      DefinitionUri: statemachines/facebook-comment-handler/machine.asl.json
      DefinitionSubstitutions:
        TableName: !Ref EntityServiceBindings
        OrchestratorName: !Ref OrchestratorFunc
        FacebookAPIFunctionArn: !GetAtt FacebookAPIFunction.Arn
        RapiDapiConnArn: !ImportValue RapidApiConnectionArnV3

      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: 
                - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:FacebookAPIService-FacebookAPIFunction-*"
                - !Ref OrchestratorFunc
                - arn:aws:lambda:us-east-1:039612842158:function:ai-service-AIServiceFunction-NVMRJ9Rl6IU7
                - arn:aws:lambda:us-east-1:039612842158:function:ai-service-AIServiceFunction-NVMRJ9Rl6IU7:*
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EntityServiceBindings}"    
            - Effect: Allow
              Action:
                - states:InvokeHTTPEndpoint
              Resource: "*"
            - Effect: Allow
              Action:
                - events:RetrieveConnectionCredentials
                - events:DescribeConnection
              Resource: !ImportValue RapidApiConnectionArnV3
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/*"
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: "*"
        
  FacebookLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: facebook-layer
      Description: Facebook API Service Layer
      ContentUri: facebook_layer/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Retain

  FacebookTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: facebook_page_tokens
      AttributeDefinitions:
        - AttributeName: page_id
          AttributeType: S
      KeySchema:
        - AttributeName: page_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST    

  FacebookWebhookRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Rule to process Facebook webhook events via state machine"
      State: ENABLED
      EventPattern:
        source:
          - facebook.webhook
        detail-type:
          - "Facebook Webhook Event"
      Targets:
        - Arn: !GetAtt FacebookCommentHandler.Arn
          Id: "FacebookWebhookTarget"
          RoleArn: !GetAtt EventBridgeRole.Arn
          InputPath: "$.detail"

  ApiGatewayCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: meta.ieva.tech
      RegionalCertificateArn: arn:aws:acm:us-east-1:039612842158:certificate/6e56d2e3-e713-41ce-85df-10092b316635
      EndpointConfiguration:
        Types:
          - REGIONAL        
